### PR TITLE
Add Autobuild on Commit

### PR DESCRIPTION
**Pull request by PrincessAkira**

### CODE REVIEW

**Comment by PrincessAkira** [comment]
Wasnt able to ZIP ot tho or upload it as a Binary.
It justt wont find it.
Idk ifu wanna try that. I tried for 2 Hours atleast

**Comment by ChrisAnd1998** [comment]
@PrincessAkira 2 hours?!! I really appreciate your effort in this! Thank you.
As soon as I get back from work I will first look into **Github Actions** and then look into this ;)

**Comment by PrincessAkira** [comment]
The Problem with this is tho
if you wanna change it or smth, you need to commit and push xD
mine works as far as uploading it as artifact via Releases

**Comment by ChrisAnd1998** [comment]
It successfully uploaded the artifact!
https://github.com/ChrisAnd1998/TaskbarXI/actions/runs/1732396999

Before trying to generate a zip file.. it needs to upload the file to the latest pre / release.
```
- name: Upload Release Asset
      uses: actions/upload-release-asset@1.0.1.0
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: D:\a\TaskbarXI\TaskbarXI\Taskbar11\Release\TaskbarXI.exe
          asset_name: TaskbarXI_nightly.exe
          asset_content_type: application/vnd.microsoft.portable-executable

```

It keeps failing on **unable to find version `1.0.1.0`**

**Comment by PrincessAkira** [comment]
> It successfully uploaded the artifact! https://github.com/ChrisAnd1998/TaskbarXI/actions/runs/1732396999
> 
> Before trying to generate a zip file.. it needs to upload the file to the latest pre / release.
> 
> ```
> - name: Upload Release Asset
>       uses: actions/upload-release-asset@1.0.1.0
>       with:
>           upload_url: ${{ steps.create_release.outputs.upload_url }}
>           asset_path: D:\a\TaskbarXI\TaskbarXI\Taskbar11\Release\TaskbarXI.exe
>           asset_name: TaskbarXI_nightly.exe
>           asset_content_type: application/vnd.microsoft.portable-executable
> ```
> 
> It keeps failing on **unable to find version `1.0.1.0`**

Yes u can manually create a Release ID with one of the Things

**Pull request merged**
